### PR TITLE
Adding RH repositories

### PR DESCRIPTION
**Pull request by edeandrea**
Adding RH repositories

### CODE REVIEW

**Comment by danieloh30** [comment]
Any specific reasons to add the repo? I think that the maven build/package still works without the repo.

**Comment by edeandrea** [comment]
It doesn't. @jamesfalkner had an issue yesterday. The `~/.m2/settings.xml` doesn't have the Red Hat repos listed in the `<activeProfiles>`. That would need to be fixed in the workspace stack.

**Comment by danieloh30** [comment]
Is that about PR that you created to upgrade Spring Boot 2.1.6? When I tested it without adding the repo, it worked to build and package. Do you know when it occurs the issue in the "break-monolith-apart2"?

**Comment by jamesfalkner** [comment]
Order a v2m2 and try to build the catalog service. It fails. Then add in the repository definition and it works.

**Comment by edeandrea** [comment]
There must be something somewhere in a base layer of the stack image thats pre-populating the local m2 repo with the `me.snowdrop` libs for the `1.5.8.Final` version, otherwise the monolith wouldn't build either. 

This seemed like the easiest solution at the moment. The other solution would be to update the stack image & modify the `~/.m2/settings.xml` to include the RH repos in the `<activeProfiles>`.

**Comment by edeandrea** [comment]
There must be something somewhere in a base layer of the stack image thats pre-populating the local m2 repo with the `me.snowdrop` libs for the `1.5.8.Final` version, otherwise the monolith wouldn't build either. 

This seemed like the easiest solution at the moment. The other solution would be to update the stack image & modify the `~/.m2/settings.xml` to include the RH repos in the `<activeProfiles>`.

**Comment by danieloh30** [comment]
@jamesfalkner @edeandrea Thanks for the clarification. I just confirmed it. I just found it that I already added the repo & plugin in 4.2 repo. :d

**Pull request merged**
