### PR TITLE
Updates for new Spring Boot version

### PR DESCRIPTION
**Pull request by edeandrea**
Update to Spring boot version 2.1.6

### CODE REVIEW

**Comment by jamesfalkner** [comment]
@edeandrea Can you also check `v2m2-labs`, `v2m3-labs`, and `v2m4-labs` ? These modules contain the "solution" source code for the spring boot (and quarkus) apps and will need the same treatment. Yeah, the duplication is sub-optimal.

**Comment by edeandrea** [comment]
Yep I'm going through all of them this week and will make necessary adjustments as I get through them all.

**Comment by danieloh30** [comment]
FYI, I already updated the latest SB version of Runtimes when I'm converting OCP 4.2. All changes are based on 4.2 branch. So @edeandrea you don't need to create a PR b/c I'm already working on it on new branch 4.2(WIP).

**Comment by edeandrea** [comment]
Thanks @danieloh30 you just saved me some work this week! Let me know if you need any help.

**Comment by danieloh30** [comment]
Sure. Thanks for your contribution. I'm revising all contents & lab codes based OCP 4.2 including screenshots. Stay tuned and I will update you soon.

**Pull request merged**
